window:
  padding:
    x: 6
    y: 10
  decorations: none
  opacity: 0.92

scrolling:
  multiplier: 3

font:
  normal:
    family: Hack
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  size: 18.0
  # use_thin_strokes: true
  # Replaced the above line with
  AppleFontSmooting: true

# Colors (Argonaut)
colors:
  # Default colors
  primary:
    background: '#100000' # almost black
    #foreground: '#8be4e1' # very light neon blue
    foreground: '#ddddee'
    #foreground: '#ffffff' # black

  # Cursor colors
  cursor:
   text:   '#000000' # black
   #text:   '#FF261E' # red?
   cursor: '#c26bff' # light magenta

  # Normal colors
  normal:
    black:   '#0d0d0d'
    red:     '#ff34b3' # executables
    green:   '#A0E521'
    yellow:  '#FFC620'
    blue:    '#1BA6FA'

  # Bright colors
  bright:
    black:   '#6D7070'
    red:     '#FF4352'
    green:   '#B8E466'
    yellow:  '#FFD750' # vim selected line number
    blue:    '#ff34b3'
    magenta: '#A578EA'
    cyan:    '#73FBF1'
    white:   '#FEFEF8'

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

# Mouse bindings
#
# Mouse bindings are specified as a list of objects, much like the key
# bindings further below.
#
# To trigger mouse bindings when an application running within Alacritty
# captures the mouse, the `Shift` modifier is automatically added as a
# requirement.
#
# Each mouse binding will specify a:
#
# - `mouse`:
#
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# - `action` (see key bindings for actions not exclusive to mouse mode)
#
# - Mouse exclusive actions:
#
#   - ExpandSelection
#       Expand the selection to the current mouse cursor location.
#
# And optionally:
#
# - `mods` (see key bindings)
#mouse_bindings:
#  - { mouse: Right,                 action: ExpandSelection }
#  - { mouse: Right,  mods: Control, action: ExpandSelection }
#  - { mouse: Middle, mode: ~Vi,     action: PasteSelection  }

key_bindings:
  # (macOS only)
  - { key: Left,           mods: Command,                    chars: "\x1bb"                }
  - { key: Right,          mods: Command,                    chars: "\x1bf"                }
  - { key: K,              mods: Command, mode: ~Vi|~Search, chars: "\x0c"                 }
  - { key: K,              mods: Command, mode: ~Vi|~Search, action: ClearHistory          }
  - { key: Key0,           mods: Command,                    action: ResetFontSize         }
  - { key: Equals,         mods: Command,                    action: IncreaseFontSize      }
  - { key: Plus,           mods: Command,                    action: IncreaseFontSize      }
  - { key: NumpadAdd,      mods: Command,                    action: IncreaseFontSize      }
  - { key: Minus,          mods: Command,                    action: DecreaseFontSize      }
  - { key: NumpadSubtract, mods: Command,                    action: DecreaseFontSize      }
  - { key: V,              mods: Command,                    action: Paste                 }
  - { key: C,              mods: Command,                    action: Copy                  }
  - { key: C,              mods: Command, mode: Vi|~Search,  action: ClearSelection        }
  - { key: H,              mods: Command,                    action: Hide                  }
  - { key: H,              mods: Command|Alt,                action: HideOtherApplications }
  - { key: M,              mods: Command,                    action: Minimize              }
  - { key: Q,              mods: Command,                    action: Quit                  }
  - { key: W,              mods: Command,                    action: Quit                  }
  - { key: N,              mods: Command,                    action: SpawnNewInstance      }
  - { key: F,              mods: Command|Control,            action: ToggleFullscreen      }
  - { key: F,              mods: Command, mode: ~Search,     action: SearchForward         }
  - { key: B,              mods: Command, mode: ~Search,     action: SearchBackward        }

